const AdminAction = {
    GET_LIST_USER : 'GET_LIST_USER',
    DETAIL_USER : 'DETAIL_USER',
    DELETE_USER: 'DELETE_USER',
    GET_LIST_SERVICE : 'GET_LIST_SERVICE',
    UPDATE_SERVICE : 'UPDATE_SERVICE',
    ADD_SERVICE: 'ADD_SERVICE',
    DELETE_SERVICE: 'DELETE_SERVICE',
    GET_LIST_AMENITY : 'GET_LIST_AMENITY',
    UPDATE_AMENITY : 'UPDATE_AMENITY',
    ADD_AMENITY: 'ADD_AMENITY',
    DELETE_AMENITY: 'DELETE_AMENITY',
}
export default AdminAction