const HostAction = {
    SAMPLE_ACTION: 'SAMPLE_ACTION',
    GET_HOTEL: 'GET_HOTEL',
    ADD_HOTEL: 'ADD_HOTEL',
    ADD_ROOM_TYPE: 'ADD_ROOM_TYPE',
    GET_ROOMTYPES: 'GET_ROOMTYPES',
    GET_ROOM_AVAILABLE: 'GET_ROOM_AVAILABLE',
    UPDATE_ROOMTYPE: 'UPDATE_ROOMTYPE'
}
export default HostAction